name       : vhba-module
version    : '20170610'
release    : 37
source     :
    - https://sourceforge.net/projects/cdemu/files/vhba-module/vhba-module-20170610.tar.bz2 : 7970c93f989d9c4f2629371bf5ee7a76f95e4c12342c3320ddc528d0df02d9ec
license    : GPL-2.0
component  :
    - kernel.drivers
    - current : kernel.drivers
summary    : Provides the vhba_ctl device for CDemu
description: |
    Provides the vhba_ctl device for CDemu
builddeps  :
    - pkgconfig(libelf)
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
rundeps    :
    - main :
        - vhba-module-common
    - current :
        - vhba-module-common
permanent  :
    - /lib/modules
patterns   :
    - common : /usr/lib64/udev
    - common : /usr/lib64/modules-load.d
    - current : /lib/modules/*.current
setup      : |
    pushd ..
    cp -a vhba-module-${version} lts-build
    cp -a vhba-module-${version} current-build
build      : |
    pushd ../lts-build
    KERNELRELEASE="%kernel_version_lts%" %make
    pushd ../current-build
    KERNELRELEASE="%kernel_version_current%" %make
install    : |
    pushd ../
    # common files
    pushd lts-build
    install -D -m 00644 $pkgfiles/60-udev.rules $installdir/%libdir%/udev/rules.d/60-vhba-module.rules
    install -D -m 00644 $pkgfiles/modprobe $installdir/%libdir%/modules-load.d/vhba-module.conf

    # lts kernel
    export KERNELRELEASE="%kernel_version_lts%"
    export KDIR="$installdir/lib/modules/${KERNELRELEASE}/kernel/drivers/misc"
    install -D -m 00644 vhba.ko $KDIR/vhba.ko
    popd

    # current kernel
    pushd current-build
    export KERNELRELEASE="%kernel_version_current%"
    export KDIR="$installdir/lib/modules/${KERNELRELEASE}/kernel/drivers/misc"
    install -D -m 00644 vhba.ko $KDIR/vhba.ko
    popd
