name       : vhba-module
version    : 20161009
release    : 1
source     :
    - https://sourceforge.net/projects/cdemu/files/vhba-module/vhba-module-20161009.tar.bz2 : cd062d8bd61ccb8137622f837a0dadb771cc935981d8bccb2ad4de0bd11f33d9
license    : GPL-2.0
component  : kernel.driver
summary    : Provides the vhba_ctl device for CDemu
description: |
    Provides the vhba_ctl device for CDemu
builddeps  :
    - linux-lts
    - linux-lts-headers
permanent  :
    - /lib/modules
build      : |
    export KERNELRELEASE="%kernel_version_lts%"
    %make 
install    : |
    export KERNELRELEASE="%kernel_version_lts%"
    export KDIR="$installdir/lib/modules/${KERNELRELEASE}/kernel/drivers/misc"
    install -D -m 00644 vhba.ko $KDIR/vhba.ko
    install -D -m 00644 $pkgfiles/60-udev.rules $installdir/%libdir%/udev/rules.d/60-vhba-module.rules
    install -D -m 00644 $pkgfiles/modprobe $installdir/%libdir%/modules-load.d/vhba-module.conf
